apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-pipeline-dev

resources:
  - ../../

namePrefix: dev-

images:
  - name: gcr.io/cisc691-a04/rag-pipeline
    newTag: dev

patchesStrategicMerge:
  - deployment-patch.yaml

replicas:
  - name: rag-pipeline
    count: 1
  - name: ollama
    count: 1