apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-pipeline-sa
  namespace: rag-pipeline
  annotations:
    iam.gke.io/gcp-service-account: rag-pipeline@cisc691-a04.iam.gserviceaccount.com