apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-pipeline-prod

resources:
  - ../../k8s/

namePrefix: prod-

images:
  - name: gcr.io/cisc691-a04/rag-pipeline
    newTag: latest

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: rag-pipeline

replicas:
  - name: rag-pipeline
    count: 2
  - name: ollama
    count: 1